### ISSUE TITLE
Improvement on error message and non base type of FalttenedType

### ISSUE THREAD

**Issue by BobAnkh** [arcjustin/btf#3]
https://github.com/arcjustin/btf/blob/771fb15e4f06f71055dd61ef507e9bc0eb31e60a/src/btf.rs#L827-L832

I have encountered a `FlattenedType has non base type` issue on linux 6.0, running your demo `print_program`. However, the error message delivers no useful information. So I suggest this to include the `non-base FalttenedType` int the `InternalError` and switch the message in `InternalError` from &str to String.

Besides, the non base type of FalttenedType is `Variable(Variable { linkage: Global })`, I would like to how to fix the issue as well.

**Comment by arcjustin** [comment]
Sorry this is happening and thanks so much for submitting this. That error is never meant to be hit and indicates an unhandled case on my part. I've included that error hoping that, if people hit it, they'd be able to report it; not much more information is needed other than the kernel version, which you provided, so I didn't include anything else in the message.

I'll be working on reliability of this crate and others over the next week including tests for BTF parsing across a wide range of kernels.

**Comment by BobAnkh** [comment]
Thank you for your work. I would like to test again when your crates are ready(handling v6.0 which is the latest stable kernel version).

**Comment by arcjustin** [comment]
Fixed in v0.5.1. Let me know if anything like this comes up again

**Comment by BobAnkh** [comment]
Thanks for your work. This is fixed in my case(kernel v6.0.0).
